### ISSUE TITLE
Extension doesn't work.

### ISSUE THREAD

**Issue by sargon2** [OddSuvius/Header-Files-Refactor#1]
I have a C++ project that uses CMake with Ninja on Windows. After enabling the extension, when I rename a header file, then no other files are updated and no error is shown.

**Comment by OddSuvius** [comment]
I hear you, I will update the extension on Thursday, currently it does not iterate over all the header files in the project

**Comment by sargon2** [comment]
Thanks.  I switched to https://github.com/tostc/CPP-include-refactor since that one works now.
